export const AUTHENTICATE_STARTED = 'AUTHENTICATE_STARTED';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR';
export const AUTHENTICATE_REMEMBER_ME = 'AUTHENTICATE_REMEMBER_ME';
export const LOGOUT = 'LOGOUT';