export const TRIP_FORM_EDIT = 'TRIP_FORM_EDIT';
export const TRIP_FORM_SENT = 'TRIP_FORM_SENT';
export const TRIP_FORM_SENDING = 'TRIP_FORM_SENDING';
export const TRIP_FORM_SEND_ERROR = 'TRIP_FORM_SEND_ERROR';
export const TRIP_FORM_CHECK_FIELDS = 'CHECK_TRIP_FORM_DATA';
